export const protocolNames: { [id: string]: string } = {
  aave: 'Aave',
  balancer: 'Balancer',
  bancor: 'Bancor Network',
  curve: 'Curve',
  hegic: 'Hegic',
  futureswap: 'Futureswap',
  omen: 'Omen',
  polymarket: 'Polymarket',
  ren: 'Ren Protocol',
  'uniswap-v2': 'Uniswap V2',
  'uniswap-v1': 'Uniswap V1',
  linkswap: 'LINKSWAP',
  sushiswap: 'SushiSwap',
  synthetix: 'Synthetix Exchange',

  eth: 'Ethereum',
  btc: 'Bitcoin',
  ltc: 'Litecoin',
  ada: 'Cardano',
  xtz: 'Tezos',
  bsv: 'Bitcoin SV',
  bch: 'Bitcoin Cash',
  xrp: 'Ripple',
  doge: 'Dogecoin',
  xmr: 'Monero',
  xlm: 'Stellar',
  bnb_mainnet: 'Binance Chain', // eslint-disable-line @typescript-eslint/camelcase
  zerox: '0x',
  mstable: 'mStable',
};
